apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-exporter-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: metrics-exporter
  endpoints:
  - port: 8000
    interval: 15s